export default {
    NAVIGATION: {
        COMPLETE: "NAVIGATION/COMPLETE"
    },
    PAGE: {
        FETCH: "PAGE/FETCH",
        FETCH_SUCCESS: "PAGE/FETCH_SUCCESS",
        UPDATE: "PAGE/UPDATE",
        UPDATE_ERROR: "PAGE/UPDATE_ERROR",
        UPDATE_SUCCESS: "PAGE/UPDATE_SUCCESS"
    },
    PAGES: {
        FETCH: "PAGES/FETCH",
        FETCH_SUCCESS: "PAGES/FETCH_SUCCESS"
    }
};
