export default {
    NAVIGATION: {
        COMPLETE: "NAVIGATION/COMPLETE"
    },
    PAGE: {
        FETCH: "PAGE/FETCH",
        FETCH_SUCCESS: "PAGE/FETCH_SUCCESS",
        CREATE: "PAGE/CREATE",
        CREATE_ERROR: "PAGE/CREATE_ERROR",
        CREATE_SUCCESS: "PAGE/CREATE_SUCCESS",
        UPDATE: "PAGE/UPDATE",
        UPDATE_ERROR: "PAGE/UPDATE_ERROR",
        UPDATE_SUCCESS: "PAGE/UPDATE_SUCCESS"
    },
    PAGES: {
        FETCH: "PAGES/FETCH",
        FETCH_SUCCESS: "PAGES/FETCH_SUCCESS"
    },
    PAGE_CONTENT: {
        CREATE: "PAGE_CONTENT/CREATE",
        CREATE_SUCCESS: "PAGE_CONTENT/CREATE_SUCCESS",
        UPDATE: "PAGE_CONTENT/UPDATE",
        UPDATE_SUCCESS: "PAGE_CONTENT/UPDATE_SUCCESS",
        DELETE: "PAGE_CONTENT/DELETE",
        DELETE_SUCCESS: "PAGE_CONTENT/DELETE_SUCCESS"
    }
};
